version: '3.7'
services:
  postgres:
    image: postgres:13.11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  web:
    build:
      context: ./
      target: local
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:example@postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres
  que:
    build:
      context: ./
      target: local
    command: bundle exec que
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:example@postgres
    depends_on:
      - postgres
    links:
      - postgres