version: '3.7'
services:
  tika:
    build: ./
    working_dir: /app
    volumes:
      - $PWD:/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432